const webConfig = {
  NEXT_PUBLIC_ETH_RPC_URL: process.env.NEXT_PUBLIC_ETH_RPC_URL ?? "",
  NEXT_PUBLIC_ETH_WSS_URL: process.env.NEXT_PUBLIC_ETH_WSS_URL ?? "",
  NEXT_PUBLIC_ETH_CHAIN_ID: process.env.NEXT_PUBLIC_ETH_CHAIN_ID ?? "",
  NEXT_PUBLIC_MANTLE_RPC_URL: process.env.NEXT_PUBLIC_MANTLE_RPC_URL ?? "",
  NEXT_PUBLIC_MANTLE_WSS_URL: process.env.NEXT_PUBLIC_MANTLE_WSS_URL ?? "",
  NEXT_PUBLIC_MANTLE_CHAIN_ID: process.env.NEXT_PUBLIC_MANTLE_CHAIN_ID ?? "",
  NEXT_PUBLIC_REOWN_PROJECT_ID: process.env.NEXT_PUBLIC_REOWN_PROJECT_ID ?? "",
} as const;

export default webConfig;
